### ISSUE TITLE
HTTP sign in causes widget to fail.

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#139]
If you sign into codesy.io as http instead of https the widget ajax calls will fail.

Any way to re-direct to an HTTPS url?

**Comment by groovecoder** [comment]
Good call.

**Comment by groovecoder** [comment]
We can auto-redirect http to https with [`django-sslify`](https://github.com/rdegges/django-sslify). But, "`django-sslify` is automatically disabled if `settings.DEBUG` is `True`."

So this wouldn't help you locally if you're running without https. And if you're running without https, the GitHub auth should fail anyway because all of the OAuth callback url's on GitHub are set to https.

**Comment by groovecoder** [comment]
WONTFIXing this based on https://github.com/codesy/codesy/issues/139#issuecomment-77726794
