### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#189]
Please explain the difference between requirement.txt and the -dev and -test variants?

**Comment by groovecoder** [comment]
`requirements.txt` is the python libraries required to run the app; `-dev` are libraries that help with dev tasks like debugging and generating docs; `-test` are libraries required for running the tests (on Travis).

They're separated so that, e.g., Heroku can only download & install the app requirements and leave the `dev` and `test` requirements out of the deploy process.
